// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

/*
Package storagepb is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	NodeIDProto
	SubtreeProto
	LogStorageConfig
	LeafDataProto
*/
package storagepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NodeIDProto is the serialized form of NodeID. It's used only for persistence in storage.
// As this is long-term we prefer not to use a Go specific format.
type NodeIDProto struct {
	Path          []byte `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	PrefixLenBits int32  `protobuf:"varint,2,opt,name=prefix_len_bits,json=prefixLenBits" json:"prefix_len_bits,omitempty"`
}

func (m *NodeIDProto) Reset()                    { *m = NodeIDProto{} }
func (m *NodeIDProto) String() string            { return proto.CompactTextString(m) }
func (*NodeIDProto) ProtoMessage()               {}
func (*NodeIDProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeIDProto) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *NodeIDProto) GetPrefixLenBits() int32 {
	if m != nil {
		return m.PrefixLenBits
	}
	return 0
}

// SubtreeProto contains nodes of a subtree.
type SubtreeProto struct {
	// subtree's prefix (must be a multiple of 8 bits)
	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// subtree's depth
	Depth    int32  `protobuf:"varint,2,opt,name=depth" json:"depth,omitempty"`
	RootHash []byte `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// map of suffix (within subtree) to subtree-leaf node hash
	Leaves map[string][]byte `protobuf:"bytes,4,rep,name=leaves" json:"leaves,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Map of suffix (within subtree) to subtree-internal node hash.
	// This structure is usually used in RAM as a cache, the internal nodes of
	// the subtree are not generally stored. However internal nodes are stored for
	// partially filled log subtrees.
	InternalNodes map[string][]byte `protobuf:"bytes,5,rep,name=internal_nodes,json=internalNodes" json:"internal_nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Used as a crosscheck on the internal node map by recording its expected size after
	// loading and repopulation.
	InternalNodeCount uint32 `protobuf:"varint,6,opt,name=internal_node_count,json=internalNodeCount" json:"internal_node_count,omitempty"`
}

func (m *SubtreeProto) Reset()                    { *m = SubtreeProto{} }
func (m *SubtreeProto) String() string            { return proto.CompactTextString(m) }
func (*SubtreeProto) ProtoMessage()               {}
func (*SubtreeProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubtreeProto) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SubtreeProto) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *SubtreeProto) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *SubtreeProto) GetLeaves() map[string][]byte {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func (m *SubtreeProto) GetInternalNodes() map[string][]byte {
	if m != nil {
		return m.InternalNodes
	}
	return nil
}

func (m *SubtreeProto) GetInternalNodeCount() uint32 {
	if m != nil {
		return m.InternalNodeCount
	}
	return 0
}

type LogStorageConfig struct {
	// num_unseq_buckets defines the length of the unsequenced time ring buffer.
	// This value must *never* be reduced for any provisioned tree while there is
	// unsequenced work for it remaining in the queue.
	//
	// This value should be >= 1, and there's probably not much benefit in
	// raising it past about 4 but this is currently unexplored territory.
	NumUnseqBuckets int64 `protobuf:"varint,1,opt,name=num_unseq_buckets,json=numUnseqBuckets" json:"num_unseq_buckets,omitempty"`
	// num_merkle_buckets defines the number of individual buckets below each
	// unsequenced ring bucket.
	// This value may be changed at any time (so long as you understand the
	// impact it'll have on integration performance!)
	//
	// This value must lie in the range [1..256]
	NumMerkleBuckets int64 `protobuf:"varint,2,opt,name=num_merkle_buckets,json=numMerkleBuckets" json:"num_merkle_buckets,omitempty"`
	// If this is set to false then bucketing is off and the bucket stored will
	// always be zero. Otherwise it's enabled and the rules listed above apply.
	EnableBuckets bool `protobuf:"varint,3,opt,name=enable_buckets,json=enableBuckets" json:"enable_buckets,omitempty"`
}

func (m *LogStorageConfig) Reset()                    { *m = LogStorageConfig{} }
func (m *LogStorageConfig) String() string            { return proto.CompactTextString(m) }
func (*LogStorageConfig) ProtoMessage()               {}
func (*LogStorageConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogStorageConfig) GetNumUnseqBuckets() int64 {
	if m != nil {
		return m.NumUnseqBuckets
	}
	return 0
}

func (m *LogStorageConfig) GetNumMerkleBuckets() int64 {
	if m != nil {
		return m.NumMerkleBuckets
	}
	return 0
}

func (m *LogStorageConfig) GetEnableBuckets() bool {
	if m != nil {
		return m.EnableBuckets
	}
	return false
}

// LeafDataProto bundles up the leaf value and extra data for log entries. This reduces the
// number of BLOB fields that the database has to insert and manage. These values are never
// queried and are always returned together anyway.
type LeafDataProto struct {
	// The leaf data - this must be set
	LeafValue []byte `protobuf:"bytes,1,opt,name=leaf_value,json=leafValue,proto3" json:"leaf_value,omitempty"`
	// The extra data - this is optional
	ExtraData []byte `protobuf:"bytes,2,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
}

func (m *LeafDataProto) Reset()                    { *m = LeafDataProto{} }
func (m *LeafDataProto) String() string            { return proto.CompactTextString(m) }
func (*LeafDataProto) ProtoMessage()               {}
func (*LeafDataProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *LeafDataProto) GetLeafValue() []byte {
	if m != nil {
		return m.LeafValue
	}
	return nil
}

func (m *LeafDataProto) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeIDProto)(nil), "storagepb.NodeIDProto")
	proto.RegisterType((*SubtreeProto)(nil), "storagepb.SubtreeProto")
	proto.RegisterType((*LogStorageConfig)(nil), "storagepb.LogStorageConfig")
	proto.RegisterType((*LeafDataProto)(nil), "storagepb.LeafDataProto")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0xdb, 0x6b, 0x13, 0x41,
	0x14, 0xc6, 0xd9, 0x6c, 0x13, 0xba, 0x27, 0xd9, 0x36, 0x1d, 0x45, 0x96, 0x8a, 0x10, 0x22, 0x4a,
	0x28, 0xb2, 0x0f, 0xfa, 0xe2, 0xe5, 0x45, 0xda, 0x0a, 0x06, 0x52, 0xd1, 0x2d, 0xfa, 0x3a, 0xcc,
	0x36, 0x27, 0xd9, 0x25, 0xbb, 0x33, 0xeb, 0x5c, 0x4a, 0xfb, 0x77, 0x08, 0xfe, 0xbd, 0x32, 0x17,
	0xc3, 0x8a, 0xf8, 0xe0, 0xdb, 0x9c, 0xef, 0x7c, 0xf3, 0xdb, 0x39, 0xdf, 0x1e, 0x48, 0x95, 0x16,
	0x92, 0x6d, 0x31, 0xef, 0xa4, 0xd0, 0x82, 0x24, 0xa1, 0xec, 0xca, 0xf9, 0x12, 0xc6, 0x9f, 0xc4,
	0x1a, 0x97, 0x97, 0x9f, 0x5d, 0x87, 0xc0, 0x41, 0xc7, 0x74, 0x95, 0x45, 0xb3, 0x68, 0x31, 0x29,
	0xdc, 0x99, 0x3c, 0x87, 0xe3, 0x4e, 0xe2, 0xa6, 0xbe, 0xa3, 0x0d, 0x72, 0x5a, 0xd6, 0x5a, 0x65,
	0x83, 0x59, 0xb4, 0x18, 0x16, 0xa9, 0x97, 0x57, 0xc8, 0xcf, 0x6b, 0xad, 0xe6, 0x3f, 0x63, 0x98,
	0x5c, 0x9b, 0x52, 0x4b, 0x44, 0x0f, 0x7b, 0x04, 0x23, 0xef, 0x08, 0xb8, 0x50, 0x91, 0x87, 0x30,
	0x5c, 0x63, 0xa7, 0xab, 0x80, 0xf1, 0x05, 0x79, 0x0c, 0x89, 0x14, 0x42, 0xd3, 0x8a, 0xa9, 0x2a,
	0x8b, 0xdd, 0x85, 0x43, 0x2b, 0x7c, 0x64, 0xaa, 0x22, 0xef, 0x60, 0xd4, 0x20, 0xbb, 0x45, 0x95,
	0x1d, 0xcc, 0xe2, 0xc5, 0xf8, 0xe5, 0xd3, 0x7c, 0x3f, 0x42, 0xde, 0xff, 0x66, 0xbe, 0x72, 0xae,
	0x0f, 0x5c, 0xcb, 0xfb, 0x22, 0x5c, 0x21, 0x5f, 0xe0, 0xa8, 0xe6, 0x1a, 0x25, 0x67, 0x0d, 0xe5,
	0x62, 0x8d, 0x2a, 0x1b, 0x3a, 0xc8, 0xd9, 0xbf, 0x20, 0xcb, 0xe0, 0xb6, 0xc9, 0x04, 0x56, 0x5a,
	0xf7, 0x35, 0x92, 0xc3, 0x83, 0x3f, 0x90, 0xf4, 0x46, 0x18, 0xae, 0xb3, 0xd1, 0x2c, 0x5a, 0xa4,
	0xc5, 0x49, 0xdf, 0x7b, 0x61, 0x1b, 0xa7, 0x6f, 0x60, 0xdc, 0x7b, 0x19, 0x99, 0x42, 0xbc, 0xc3,
	0x7b, 0x17, 0x4b, 0x52, 0xd8, 0xa3, 0xcd, 0xe4, 0x96, 0x35, 0x06, 0x5d, 0x26, 0x93, 0xc2, 0x17,
	0x6f, 0x07, 0xaf, 0xa3, 0xd3, 0xf7, 0x40, 0xfe, 0x7e, 0xcf, 0xff, 0x10, 0xe6, 0x3f, 0x22, 0x98,
	0xae, 0xc4, 0xf6, 0xda, 0x0f, 0x7b, 0x21, 0xf8, 0xa6, 0xde, 0x92, 0x33, 0x38, 0xe1, 0xa6, 0xa5,
	0x86, 0x2b, 0xfc, 0x4e, 0x4b, 0x73, 0xb3, 0x43, 0xad, 0x1c, 0x2e, 0x2e, 0x8e, 0xb9, 0x69, 0xbf,
	0x5a, 0xfd, 0xdc, 0xcb, 0xe4, 0x05, 0x10, 0xeb, 0x6d, 0x51, 0xee, 0x1a, 0xdc, 0x9b, 0x07, 0xce,
	0x3c, 0xe5, 0xa6, 0xbd, 0x72, 0x8d, 0xdf, 0xee, 0x67, 0x70, 0x84, 0x9c, 0x95, 0x3d, 0xa7, 0xfd,
	0x9b, 0x87, 0x45, 0xea, 0xd5, 0x60, 0x9b, 0x5f, 0x41, 0xba, 0x42, 0xb6, 0xb9, 0x64, 0x9a, 0xf9,
	0x75, 0x79, 0x02, 0xd0, 0x20, 0xdb, 0x50, 0x3f, 0x85, 0x5f, 0x99, 0xc4, 0x2a, 0xdf, 0xac, 0x60,
	0xdb, 0x78, 0xa7, 0x25, 0xa3, 0x6b, 0xa6, 0x59, 0x18, 0x32, 0x71, 0x8a, 0x45, 0x94, 0x23, 0xb7,
	0xda, 0xaf, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x09, 0x34, 0x84, 0x2e, 0xeb, 0x02, 0x00, 0x00,
}
