// Code generated by protoc-gen-go.
// source: storage.proto
// DO NOT EDIT!

/*
Package storagepb is a generated protocol buffer package.

It is generated from these files:
	storage.proto

It has these top-level messages:
	NodeIDProto
	SubtreeProto
	LeafDataProto
*/
package storagepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// NodeIDProto is the serialized form of NodeID. It's used only for persistence in storage.
// As this is long-term we prefer not to use a Go specific format.
type NodeIDProto struct {
	Path          []byte `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	PrefixLenBits int32  `protobuf:"varint,2,opt,name=prefix_len_bits,json=prefixLenBits" json:"prefix_len_bits,omitempty"`
}

func (m *NodeIDProto) Reset()                    { *m = NodeIDProto{} }
func (m *NodeIDProto) String() string            { return proto.CompactTextString(m) }
func (*NodeIDProto) ProtoMessage()               {}
func (*NodeIDProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeIDProto) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *NodeIDProto) GetPrefixLenBits() int32 {
	if m != nil {
		return m.PrefixLenBits
	}
	return 0
}

// SubtreeProto contains nodes of a subtree.
type SubtreeProto struct {
	// subtree's prefix (must be a multiple of 8 bits)
	Prefix []byte `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// subtree's depth
	Depth    int32  `protobuf:"varint,2,opt,name=depth" json:"depth,omitempty"`
	RootHash []byte `protobuf:"bytes,3,opt,name=root_hash,json=rootHash,proto3" json:"root_hash,omitempty"`
	// map of suffix (within subtree) to subtree-leaf node hash
	Leaves map[string][]byte `protobuf:"bytes,4,rep,name=leaves" json:"leaves,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Map of suffix (within subtree) to subtree-internal node hash.
	// This structure is usually used in RAM as a cache, the internal nodes of
	// the subtree are not generally stored. However internal nodes are stored for
	// partially filled log subtrees.
	InternalNodes map[string][]byte `protobuf:"bytes,5,rep,name=internal_nodes,json=internalNodes" json:"internal_nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Used as a crosscheck on the internal node map by recording its expected size after
	// loading and repopulation.
	InternalNodeCount uint32 `protobuf:"varint,6,opt,name=internal_node_count,json=internalNodeCount" json:"internal_node_count,omitempty"`
}

func (m *SubtreeProto) Reset()                    { *m = SubtreeProto{} }
func (m *SubtreeProto) String() string            { return proto.CompactTextString(m) }
func (*SubtreeProto) ProtoMessage()               {}
func (*SubtreeProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubtreeProto) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *SubtreeProto) GetDepth() int32 {
	if m != nil {
		return m.Depth
	}
	return 0
}

func (m *SubtreeProto) GetRootHash() []byte {
	if m != nil {
		return m.RootHash
	}
	return nil
}

func (m *SubtreeProto) GetLeaves() map[string][]byte {
	if m != nil {
		return m.Leaves
	}
	return nil
}

func (m *SubtreeProto) GetInternalNodes() map[string][]byte {
	if m != nil {
		return m.InternalNodes
	}
	return nil
}

func (m *SubtreeProto) GetInternalNodeCount() uint32 {
	if m != nil {
		return m.InternalNodeCount
	}
	return 0
}

// LeafDataProto bundles up the leaf value and extra data for log entries. This reduces the
// number of BLOB fields that the database has to insert and manage. These values are never
// queried and are always returned together anyway.
type LeafDataProto struct {
	// The leaf data - this must be set
	LeafValue []byte `protobuf:"bytes,1,opt,name=leaf_value,json=leafValue,proto3" json:"leaf_value,omitempty"`
	// The extra data - this is optional
	ExtraData []byte `protobuf:"bytes,2,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
}

func (m *LeafDataProto) Reset()                    { *m = LeafDataProto{} }
func (m *LeafDataProto) String() string            { return proto.CompactTextString(m) }
func (*LeafDataProto) ProtoMessage()               {}
func (*LeafDataProto) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LeafDataProto) GetLeafValue() []byte {
	if m != nil {
		return m.LeafValue
	}
	return nil
}

func (m *LeafDataProto) GetExtraData() []byte {
	if m != nil {
		return m.ExtraData
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeIDProto)(nil), "storagepb.NodeIDProto")
	proto.RegisterType((*SubtreeProto)(nil), "storagepb.SubtreeProto")
	proto.RegisterType((*LeafDataProto)(nil), "storagepb.LeafDataProto")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x92, 0x4f, 0x4b, 0xeb, 0x40,
	0x14, 0xc5, 0x49, 0xd3, 0x86, 0x97, 0xdb, 0xe6, 0xbd, 0xe7, 0x28, 0x12, 0x2a, 0x42, 0xa8, 0x20,
	0xc1, 0x45, 0x16, 0xba, 0xf1, 0xcf, 0x46, 0xb4, 0x82, 0x85, 0x2a, 0x1a, 0xc1, 0x6d, 0x98, 0x98,
	0x5b, 0x13, 0x0c, 0x99, 0x30, 0x33, 0x2d, 0xed, 0x17, 0xf1, 0xf3, 0xca, 0xfc, 0x41, 0x22, 0xe2,
	0xc2, 0xdd, 0x9c, 0x73, 0xcf, 0xfc, 0x32, 0x39, 0x33, 0x10, 0x08, 0xc9, 0x38, 0x7d, 0xc5, 0xa4,
	0xe5, 0x4c, 0x32, 0xe2, 0x5b, 0xd9, 0xe6, 0x93, 0x19, 0x0c, 0xef, 0x59, 0x81, 0xb3, 0xe9, 0x83,
	0x9e, 0x10, 0xe8, 0xb7, 0x54, 0x96, 0xa1, 0x13, 0x39, 0xf1, 0x28, 0xd5, 0x6b, 0x72, 0x08, 0xff,
	0x5a, 0x8e, 0x8b, 0x6a, 0x9d, 0xd5, 0xd8, 0x64, 0x79, 0x25, 0x45, 0xd8, 0x8b, 0x9c, 0x78, 0x90,
	0x06, 0xc6, 0x9e, 0x63, 0x73, 0x55, 0x49, 0x31, 0x79, 0x77, 0x61, 0xf4, 0xb4, 0xcc, 0x25, 0x47,
	0x34, 0xb0, 0x5d, 0xf0, 0x4c, 0xc2, 0xe2, 0xac, 0x22, 0x3b, 0x30, 0x28, 0xb0, 0x95, 0xa5, 0xc5,
	0x18, 0x41, 0xf6, 0xc0, 0xe7, 0x8c, 0xc9, 0xac, 0xa4, 0xa2, 0x0c, 0x5d, 0xbd, 0xe1, 0x8f, 0x32,
	0x6e, 0xa9, 0x28, 0xc9, 0x05, 0x78, 0x35, 0xd2, 0x15, 0x8a, 0xb0, 0x1f, 0xb9, 0xf1, 0xf0, 0xf8,
	0x20, 0xf9, 0xfc, 0x85, 0xa4, 0xfb, 0xcd, 0x64, 0xae, 0x53, 0x37, 0x8d, 0xe4, 0x9b, 0xd4, 0x6e,
	0x21, 0x8f, 0xf0, 0xb7, 0x6a, 0x24, 0xf2, 0x86, 0xd6, 0x59, 0xc3, 0x0a, 0x14, 0xe1, 0x40, 0x43,
	0x8e, 0x7e, 0x82, 0xcc, 0x6c, 0x5a, 0x35, 0x63, 0x59, 0x41, 0xd5, 0xf5, 0x48, 0x02, 0xdb, 0x5f,
	0x90, 0xd9, 0x0b, 0x5b, 0x36, 0x32, 0xf4, 0x22, 0x27, 0x0e, 0xd2, 0xad, 0x6e, 0xf6, 0x5a, 0x0d,
	0xc6, 0x67, 0x30, 0xec, 0x9c, 0x8c, 0xfc, 0x07, 0xf7, 0x0d, 0x37, 0xba, 0x16, 0x3f, 0x55, 0x4b,
	0xd5, 0xc9, 0x8a, 0xd6, 0x4b, 0xd4, 0x9d, 0x8c, 0x52, 0x23, 0xce, 0x7b, 0xa7, 0xce, 0xf8, 0x12,
	0xc8, 0xf7, 0xf3, 0xfc, 0x86, 0x30, 0xb9, 0x83, 0x60, 0x8e, 0x74, 0x31, 0xa5, 0x92, 0x9a, 0x8b,
	0xd9, 0x07, 0xa8, 0x91, 0x2e, 0x32, 0x93, 0x37, 0x97, 0xe3, 0x2b, 0xe7, 0x59, 0x19, 0x6a, 0x8c,
	0x6b, 0xc9, 0x69, 0x56, 0x50, 0x49, 0x2d, 0xce, 0xd7, 0x8e, 0x42, 0xe4, 0x9e, 0x7e, 0x44, 0x27,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd8, 0xfe, 0xc3, 0x36, 0x55, 0x02, 0x00, 0x00,
}
